version: '3'

services:
  # Web Server
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/html:/var/www:ro
    ports:
      - "8080:80"

  sass:
    build: 
      context: .
      dockerfile: ./docker/sass/Dockerfile
    volumes:
      - ./src:/src
      - ./node_modules:/node_modules